# config/packages/security.yaml
security:

    # Comment hasher les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Comment Symfony charge un User depuis la BDD
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal : tout le site
        main:
            lazy: true
            provider: app_user_provider

            # Formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: event_index
                username_parameter: username
                password_parameter: password

            # Logout
            logout:
                path: app_logout
                target: event_index

    # Contrôle d'accès par URL
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }